description = {
    "AspN": {"Basic Info":"Aspergillus niger, a common species of fungus in the genus Aspergillus, belongs to the subphylum Pezizomycotina, class Eurotiomycetes, order Eurotiales, and family Trichocomaceae. Aspergillus niger is a primary species used in the production of soy sauce, brewing, and vinegar. It is also employed in the production of enzyme preparations (proteases, amylases, pectinases). Furthermore, it is involved in the production of organic acids such as citric acid and gluconic acid, and it is used in agriculture for the production of saccharification feed. It can be utilized for the determination of trace elements such as manganese, copper, molybdenum, and zinc, and it serves as a test fungus for mold decay.",
             "Feature & Habit":"""Based on morphology, there are two types of Aspergillus niger: sporulating Aspergillus niger and non-sporulating Aspergillus niger. Sporulating Aspergillus niger forms mature colonies with a black-brown color, and its spores are radiating, mostly distributed in the rhizosphere soil of plants. It is commonly used as a biotechnological bacterium in the field of soil remediation. Non-sporulating Aspergillus niger forms granular colonies with short and robust hyphae. It can secrete various digestive enzymes such as phytase, cellulase, and protease. It is an important host bacterium in the fermentation industry and is often used in large-scale fermentation engineering after mutagenic breeding.
             Its optimal growth temperature is 35°C, with a pH range of 3 to 7 being suitable.
             Cultivation Characteristics:
             (1) Rapid growth on Sabouraud agar, maturing within 3 days. Initially, it appears as white fluffy, gradually turning very pale yellow in the center of the colony, and finally becoming coarse and fluffy black or black-brown. The backside is colorless or pale yellow.
             (2) On potato glucose agar, the colony characteristics are similar to those on Sabouraud agar, with the colony surface having black particles larger than those on Sabouraud agar.
             (3) On Czapek-Dox agar, growth is rapid, with a velvety or slightly flocculent texture, and a few strains may exhibit more localized growth. The surface is dark brown to charcoal black, while the reverse side is colorless or pale yellow. Compared to SDA and PDA, growth on Czapek-Dox agar is slightly slower, and black particles on the colony surface are sparse.
             (4) On Potato Dextrose Agar (PDA), colonies grow rapidly, reaching a diameter of 25-3cm within 10-14 days. Colonies start as white, often with fresh yellow regions, then become thick and fluffy, and eventually turn black. The backside is colorless or slightly brown in the central part.
             Morphological Characteristics:
             (1) The fungal colony appears black-brown, with spherical conidia that are black or black-brown, smooth, or rough. The hyphae are well-developed, with septa and multiple branches.
             (2) At the top, spherical vesicles are formed, covered entirely by a layer of stalk bases and a layer of conidiophores. The conidiophores bear clusters of brown-black spherical structures, with a diameter of 2.5-4.0μm.
             (3) The conidial heads are spherical or radiating, resembling chrysanthemums, with a diameter of 700-800μm and a brown-black color. They spread rapidly, initially white, then turning bright yellow until black and thickly fluffy. The reverse side is colorless or slightly yellow-brown in the center.
             (4) Conidiophore stalks arise perpendicularly from specialized, thick-walled hyphal cells (foot cells), varying in length.
             (5) The hyphae and conidial heads of Aspergillus niger often exhibit various colors such as black, brown, green, yellow, orange, and brown. Different strains may display different colors.
             """, 
             "Potential Hazards": """(1) Aspergillus niger is the most commonly isolated fungus in fungal ear infections of immunocompetent individuals, and it can also cause deep-seated fungal infections in immunocompromised patients, leading to conditions such as fungal keratitis.
             (2) Apart from causing aspergillosis, Aspergillus niger can also produce black mold toxins.
             (3) Contamination during cheese maturation can result in blackening and spoilage of the cheese surface, and it can also cause discoloration in cream.
             (4) Aspergillus niger can cause lung infections."""},
    "AspO": {"Basic Info":"Aspergillus ochraceus is a mold species in the genus Aspergillus known to produce the toxin ochratoxin A, one of the most abundant food-contaminating mycotoxins, and citrinin. It also produces the dihydroisocoumarin mellein. It is a filamentous fungus in nature and has characteristic biseriate conidiophores.",
             "Health Hazards":"The production ability of ochratoxin A (OTA) by Aspergillus ochraceus is very strong. Its spores scattered in the air can induce asthma in children and human lung diseases. The secondary metabolite OTA is widely distributed in agricultural products, contaminating grains, grapes, feed, beverages, legumes, etc. In addition, it has been found in some animal by-products such as milk, animal kidneys, liver, and blood, and can eventually enter the human body through the food chain, seriously endangering human health. OTA can cause liver and kidney damage in animals and humans, as well as teratogenic, mutagenic, carcinogenic, and immunosuppressive effects. It may also be associated with Balkan endemic nephropathy and urinary system tumors and is classified as a Group 2B potential carcinogen by the International Agency for Research on Cancer.",
             "Feature & Habit":"Aspergillus ochraceus is a toxin-producing fungus, and its isolation and culture are commonly performed using Sabouraud agar. In grain-based culture media, broken wheat is the best substrate for toxin production. The optimal growth conditions for toxin-producing molds are typically at 25-28°C, with high humidity and incubation in dark, still conditions for 1-2 weeks yielding the best toxin production results."},
    "Gla": {"Basic Info":"The genus Gladaxporism is a genus within the order Moniliales, consisting of saprophytic fungi and plant pathogens such as Cladosporium fulvum, which is the pathogen responsible for tomato leaf mold. Its vegetative body consists of septate mycelium, long, oval-shaped, non-septate or singly septate dark conidiophores, which develop in chains at the apex of the conidiophore stalk, with clustered small conidiophores at the tip."},
    "PPoly": {"Basic Info":"The Paenibacillus polymyxa is a gram-positive bacterium of the Bacillaceae family of the Paenibacillus genus, also known as the polymyxin bacterium. The cells of Paenibacillus polymyxa are rod-shaped, gram-stained positive, negative, or variable, positive for contact enzymes, variable in oxidative enzyme reactions, and most strains fix nitrogen under anaerobic conditions. The United States Environmental Protection Agency (EPA) lists it as one of the commercially applicable microorganisms, and the Ministry of Agriculture of China also lists it as a first-class species exempt from safety identification.", 
              "Taxonomy":"""The Paenibacillus polymyxa, originally known as Bacillus polymyxa, belonged to the genus Bacillus, but through phylogenetic analysis of the 16S rRNA gene sequence, it was found to have significant differences from other species within the Bacillus genus. Therefore, in 1993, it was reclassified into a new genus called Paenibacillus. The Paenibacillus genus includes 10 species, and by combining 16S rRNA gene sequence analysis with fatty acid composition analysis, it is possible to clearly distinguish Paenibacillus polymyxa from other species within the same genus.
              The taxonomic status of Paenibacillus polymyxa: Originally named Bacillus polymyxa, Paenibacillus polymyxa was initially classified under the genus Bacillus based on morphology. In 1994, Ash et al. conducted PCR probe tests and analyzed the 16S rRNA sequences of several Bacillus strains, discovering significant differences in phenotypic characteristics and highly specific 16S rRNA sequences between certain Bacillus strains and other Bacillus strains. Based on these research findings, Ash separated 11 species, including Bacillus polymyxa, from the genus Bacillus and established the genus Paenibacillus, designating Paenibacillus polymyxa as the type species of the genus. To date, the genus Paenibacillus comprises 23 species. Cells of Paenibacillus polymyxa are rod-shaped, and they may exhibit positive, negative, or variable Gram staining. They are positive for catalase, and their oxidase reaction varies. Most strains of Paenibacillus polymyxa fix nitrogen under anaerobic conditions.""",
              "Feature & Habit":"""Paenibacillus polymyxa belongs to the phylum Firmicutes, class Bacilli, order Bacillales, family Paenibacillaceae, and genus Paenibacillus. It is a type of microbial fungicide. When inoculated on LB solid culture medium and incubated at 28°C for 24 hours, the following observations can be made: the colonies are creamy in color and moist and smooth in texture. The cells are straight or nearly straight rods, measuring 2-5μm in length and 0.6-0.8μm in width, with capsules and peritrichous flagella. Oval-shaped spores cause swelling of sporangia, with sporulation occurring centrally to terminally. On PDA plates, the colonies are relatively small, white or light yellow, circular, slightly convex or not convex, with neat edges, glossy surfaces, smooth and moist textures, and semi-transparent to opaque appearance. On beef extract agar, the colonies are thinner, grayish-white, moist and smooth, without a pellicle, and the liquid is clear. On slant culture medium, growth is good, with filamentous and flat colonies, smooth surfaces, and semi-transparent appearance.
              Facultative anaerobic, producing acid by decomposing glucose and other sugars. Can be killed by ultraviolet light. Stable at pH 4-7, the product is stable when stored at 5°C or room temperature for up to 2 years.""",
              "Metabolism":"""The following are metabolic produce from Paenibacillus polymyxa:
              (1) Extracellular polysaccharides: Extracellular polysaccharides are important products that possess various functions such as emulsification, suspension aid, heavy metal enrichment, antioxidant activity, and inhibition of tumor cell growth. Typically, extracellular polysaccharides are composed of one or several sugars including glucose, galactose, glucan, fructan, mannose, allose, and glucuronic acid. In addition to fructan, Paenibacillus polymyxa can also metabolize to produce β-glucan.
              (2) Antibacterial substances: P. polymyxa produces antibacterial substances with different molecular weights, including high-molecular-weight antagonistic proteins or enzymes, low-molecular-weight peptide antibiotics, and nucleoside substances. Antibacterial proteins are mainly produced by ribosome metabolic pathways and can specifically degrade the host bacterial cell wall. These large-molecular-weight antagonistic proteins (enzymes) include β-1,3-glucanase, chitinase, protease, and pectinase. Additionally, P. polymyxa can also produce various non-enzyme proteins that still exhibit good antagonistic effects against specific plant pathogens.
              (3) Plant hormones: P. polymyxa can produce various plant growth hormones such as indole-3-acetic acid, auxin, ethylene, gibberellins, and cytokinins derived from adenine derivatives to promote crop growth and development. Treating peanut seeds with P. polymyxa HK4 results in a higher germination rate compared to the control group. Treatment with P. polymyxa 92 significantly increases mitosis in wheat, with root length increasing by 22% and root dry weight increasing by 28%.
              (4) Others: Chemical composition analysis of P. polymyxa metabolites revealed the presence of a flavonoid substance (kaempferol). Kaempferol has various effects such as inhibiting inflammation, promoting apoptosis, and regulating steroid hormone receptors and metabolic pathways, showing broad prospects in disease prevention and treatment. Additionally, P. polymyxa can metabolize to produce hydroxybenzaldehyde, pectinase, and phenazine-1-carboxylic acid (PCA). Phenazine-1-carboxylic acid synthesized by P. polymyxa SCE2 has excellent inhibitory effects on plant pathogens and also has medicinal bactericidal and anti-tumor effects. The β-glucanase and xylanase produced by P. polymyxa can effectively degrade non-starch polysaccharides, thereby expanding the range of raw material utilization in microbial manufacturing processes. The "elements" and "routes" involved in its metabolic pathway also provide ideas for constructing engineered bacteria for heterologous expression of enzyme systems in synthetic biology.""",
              "Potential Applications":"""Paenibacillus polymyxa, as a type of Plant Growth Promoting Rhizobacteria (PGPR), can enhance plant growth and increase crop yield.
              (1) As a microbial fertilizer: Paenibacillus polymyxa can promote the absorption of substances such as nitrogen, phosphorus, and potassium by plants through biological nitrogen fixation, phosphorus solubilization, potassium solubilization, etc. It can also promote symbiosis between beneficial microorganisms and plants. It helps in the remediation of soil contaminated with organic pollutants, thereby improving the environment and promoting plant growth.
              (2) Production of plant hormones: Paenibacillus polymyxa can secrete plant hormones to promote root growth and influence root morphology.
              (3) Induction of plant resistance: Plants themselves have inherent defense mechanisms against plant pathogens, which can be induced by pathogens or PGPR strains.
              (4) Biological control: Paenibacillus polymyxa inhibits the growth and invasion of pathogens through competition and antagonism, effectively controlling bacterial and fungal soil-borne diseases in plants. It has good preventive effects on diseases such as bacterial wilt, tomato wilt, cabbage rot, and pine root rot, and can also control various plant diseases caused by oomycetes and nematodes."""}}